baseURL = 'https://belshikun.github.io/'
languageCode = 'en-us'
title = 'Frog Urn Citadel'

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
[[menu.main]]
    name = "Diary"
    url = "/diary"
    weight = 3
[[menu.main]]
    name = "D&D"
    url = "/dnd"
    weight = 4
[[menu.main]]
    name = "Misc"
    url = "/misc"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 6
